addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.9.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "2.0.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.0.1")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "0.6.8")
addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "2.0.3")
